pdtg:
  brewery:
    beerInventoryServiceHost: Http://localhost:8082
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSizeLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultsSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      